image: docker:git
services:
- docker:dind

stages:
- build
- release

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/yingray/pawees_portal:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/yingray/pawees_portal:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

release-image:
  stage: release
  script:
   # try to clone yourself, the SSH_PRIVATE_KEY was added as deploy key to this repository
    - git clone git@gitlab.com:yingray/pawees_portal.git
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    # - master
    - branches
